name: 'Issue Label Actions'

on:
  issues:
    types: [labeled, unlabeled]

permissions:
  contents: read
  issues: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@102faf474a544be75fbaf4df54e73d3c515a0e65
